/** Curated kid-friendly account avatars, searchable by keyword. */
const ACCOUNT_EMOJIS: { emoji: string; keywords: string[] }[] = [
  { emoji: "🦄", keywords: ["unicorn", "magic", "horse", "fantasy"] },
  { emoji: "🚀", keywords: ["rocket", "space", "blast"] },
  { emoji: "🎨", keywords: ["art", "paint", "creative"] },
  { emoji: "⚽", keywords: ["soccer", "football", "sport", "ball"] },
  { emoji: "🏀", keywords: ["basketball", "sport", "ball"] },
  { emoji: "🏈", keywords: ["football", "sport", "ball"] },
  { emoji: "⚾", keywords: ["baseball", "sport", "ball"] },
  { emoji: "🎾", keywords: ["tennis", "sport", "ball"] },
  { emoji: "🐱", keywords: ["cat", "kitten", "pet", "animal"] },
  { emoji: "🐶", keywords: ["dog", "puppy", "pet", "animal"] },
  { emoji: "🐰", keywords: ["bunny", "rabbit", "pet", "animal"] },
  { emoji: "🐻", keywords: ["bear", "animal"] },
  { emoji: "🐼", keywords: ["panda", "bear", "animal"] },
  { emoji: "🦊", keywords: ["fox", "animal"] },
  { emoji: "🐯", keywords: ["tiger", "animal", "cat"] },
  { emoji: "🦁", keywords: ["lion", "animal", "cat"] },
  { emoji: "🐸", keywords: ["frog", "animal"] },
  { emoji: "🐵", keywords: ["monkey", "animal"] },
  { emoji: "🐧", keywords: ["penguin", "bird", "animal"] },
  { emoji: "🐦", keywords: ["bird", "animal"] },
  { emoji: "🦋", keywords: ["butterfly", "insect", "animal"] },
  { emoji: "🐝", keywords: ["bee", "insect", "animal", "honey"] },
  { emoji: "🐢", keywords: ["turtle", "animal"] },
  { emoji: "🐙", keywords: ["octopus", "ocean", "animal"] },
  { emoji: "🐬", keywords: ["dolphin", "ocean", "animal"] },
  { emoji: "🐳", keywords: ["whale", "ocean", "animal"] },
  { emoji: "🦈", keywords: ["shark", "ocean", "animal"] },
  { emoji: "🦖", keywords: ["dinosaur", "tRex", "dino"] },
  { emoji: "🦕", keywords: ["dinosaur", "dino", "long neck"] },
  { emoji: "🐉", keywords: ["dragon", "fantasy"] },
  { emoji: "🧚", keywords: ["fairy", "magic", "fantasy"] },
  { emoji: "🧙", keywords: ["wizard", "magic", "fantasy"] },
  { emoji: "🦸", keywords: ["superhero", "hero"] },
  { emoji: "🥷", keywords: ["ninja", "hero"] },
  { emoji: "👻", keywords: ["ghost", "halloween", "spooky"] },
  { emoji: "🎃", keywords: ["pumpkin", "halloween"] },
  { emoji: "👽", keywords: ["alien", "space"] },
  { emoji: "🤖", keywords: ["robot", "bot"] },
  { emoji: "⭐", keywords: ["star", "space"] },
  { emoji: "🌟", keywords: ["star", "sparkle", "shine"] },
  { emoji: "🌙", keywords: ["moon", "night", "space"] },
  { emoji: "☀️", keywords: ["sun", "day", "bright"] },
  { emoji: "🌈", keywords: ["rainbow", "color", "pride"] },
  { emoji: "☁️", keywords: ["cloud", "sky", "weather"] },
  { emoji: "❄️", keywords: ["snow", "winter", "cold"] },
  { emoji: "🔥", keywords: ["fire", "hot", "flame"] },
  { emoji: "💧", keywords: ["water", "drop", "rain"] },
  { emoji: "🌸", keywords: ["flower", "cherry", "blossom", "spring"] },
  { emoji: "🌺", keywords: ["flower", "hibiscus", "tropical"] },
  { emoji: "🌻", keywords: ["sunflower", "flower"] },
  { emoji: "🍀", keywords: ["clover", "lucky", "leaf"] },
  { emoji: "🌳", keywords: ["tree", "nature"] },
  { emoji: "🍕", keywords: ["pizza", "food"] },
  { emoji: "🍔", keywords: ["burger", "hamburger", "food"] },
  { emoji: "🍦", keywords: ["ice cream", "dessert", "food", "treat"] },
  { emoji: "🍩", keywords: ["donut", "doughnut", "dessert", "food"] },
  { emoji: "🍪", keywords: ["cookie", "dessert", "food"] },
  { emoji: "🎂", keywords: ["cake", "birthday", "dessert", "food"] },
  { emoji: "🧁", keywords: ["cupcake", "dessert", "food"] },
  { emoji: "🍎", keywords: ["apple", "fruit", "food"] },
  { emoji: "🍌", keywords: ["banana", "fruit", "food"] },
  { emoji: "🍓", keywords: ["strawberry", "fruit", "food"] },
  { emoji: "🍉", keywords: ["watermelon", "fruit", "food"] },
  { emoji: "🍇", keywords: ["grapes", "fruit", "food"] },
  { emoji: "🥕", keywords: ["carrot", "vegetable", "food"] },
  { emoji: "🎮", keywords: ["game", "controller", "video game"] },
  { emoji: "🎲", keywords: ["dice", "game", "board game"] },
  { emoji: "🧩", keywords: ["puzzle", "game"] },
  { emoji: "🎸", keywords: ["guitar", "music", "instrument"] },
  { emoji: "🎹", keywords: ["piano", "music", "keyboard", "instrument"] },
  { emoji: "🥁", keywords: ["drums", "music", "instrument"] },
  { emoji: "🎺", keywords: ["trumpet", "music", "instrument"] },
  { emoji: "🎻", keywords: ["violin", "music", "instrument"] },
  { emoji: "🎤", keywords: ["microphone", "sing", "music"] },
  { emoji: "🎧", keywords: ["headphones", "music"] },
  { emoji: "📚", keywords: ["books", "read", "library", "school"] },
  { emoji: "✏️", keywords: ["pencil", "draw", "write", "school"] },
  { emoji: "🎒", keywords: ["backpack", "school"] },
  { emoji: "🚲", keywords: ["bike", "bicycle", "ride"] },
  { emoji: "🛴", keywords: ["scooter", "ride"] },
  { emoji: "🛹", keywords: ["skateboard", "skate", "ride"] },
  { emoji: "🚗", keywords: ["car", "vehicle"] },
  { emoji: "🚕", keywords: ["taxi", "car", "vehicle"] },
  { emoji: "🚌", keywords: ["bus", "vehicle", "school"] },
  { emoji: "✈️", keywords: ["plane", "airplane", "fly", "travel"] },
  { emoji: "🚁", keywords: ["helicopter", "fly"] },
  { emoji: "⛵", keywords: ["sailboat", "boat", "sail"] },
  { emoji: "🚂", keywords: ["train", "locomotive"] },
  { emoji: "👑", keywords: ["crown", "king", "queen", "royal"] },
  { emoji: "💎", keywords: ["gem", "diamond", "jewel"] },
  { emoji: "🔮", keywords: ["crystal", "ball", "magic"] },
  { emoji: "🏆", keywords: ["trophy", "win", "award"] },
  { emoji: "🥇", keywords: ["medal", "gold", "win", "first"] },
  { emoji: "🎯", keywords: ["target", "bullseye", "aim"] },
  { emoji: "💡", keywords: ["idea", "light", "bulb", "smart"] },
  { emoji: "🧡", keywords: ["heart", "orange", "love"] },
  { emoji: "💙", keywords: ["heart", "blue", "love"] },
  { emoji: "💚", keywords: ["heart", "green", "love"] },
  { emoji: "💜", keywords: ["heart", "purple", "love"] },
  { emoji: "🩷", keywords: ["heart", "pink", "love"] },
  { emoji: "💛", keywords: ["heart", "yellow", "love"] },
  { emoji: "😀", keywords: ["smile", "happy", "face"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "face"] },
  { emoji: "🤓", keywords: ["nerd", "glasses", "smart", "face"] },
  { emoji: "🥳", keywords: ["party", "celebrate", "face"] },
  { emoji: "😇", keywords: ["angel", "halo", "innocent", "face"] },
  { emoji: "🤩", keywords: ["star eyes", "excited", "wow", "face"] },
  { emoji: "😍", keywords: ["heart eyes", "love", "face"] },
];

export function filterAccountEmojis(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return ACCOUNT_EMOJIS;
  return ACCOUNT_EMOJIS.filter(
    (item) => item.emoji.includes(q) || item.keywords.some((keyword) => keyword.includes(q)),
  );
}
