import { defineConfig } from "oxlint";

const ignorePatterns = [
  "dist/**",
  "node_modules/**",
  "**/*.js",
  "**/*.mjs",
  "2013-gender-reveal/**",
  "2014-gender-reveal/**",
  "2024/**",
  "baby/**",
  "oliviabday2011/**",
  "passports/**",
  "pt/**",
  "resurrection-challenge/**",
  "sightwords/**",
];

export default defineConfig({
  ignorePatterns,
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "import",
    "react",
    "jsx-a11y",
    "node",
    "promise",
  ],
  env: {
    browser: true,
    builtin: true,
  },
  options: {
    typeAware: true,
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
  },
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    pedantic: "error",
    nursery: "off",
  },
  rules: {
    // Unreasonable for application code / React.
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/explicit-member-accessibility": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-null": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-reduce": "off",
    "no-magic-numbers": "off",
    "id-length": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-params": "off",
    "max-depth": "off",
    "no-undefined": "off",
    "no-void": "off",
    "no-ternary": "off",
    "no-inline-comments": "off",
    "no-warning-comments": "off",
    "capitalized-comments": "off",
    "sort-keys": "off",
    "sort-imports": "off",
    "one-var": "off",
    "func-names": "off",
    "func-style": "off",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-console": "error",
    "typescript/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "separate-type-imports" },
    ],
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/strict-boolean-expressions": [
      "error",
      {
        allowNumber: true,
        allowString: true,
        allowNullableObject: true,
        allowNullableBoolean: false,
        allowNullableNumber: false,
        allowNullableString: false,
        allowAny: false,
      },
    ],
  },
  overrides: [
    {
      files: ["scripts/**", "vite.config.ts", "oxlint.config.ts", "oxfmt.config.ts"],
      env: {
        node: true,
      },
      rules: {
        "no-console": "off",
      },
    },
  ],
});
