import { defineConfig } from "oxlint";

const ignorePatterns = [
  "dist/**",
  "node_modules/**",
  "**/*.js",
  "**/*.mjs",
  "2013-gender-reveal/**",
  "2014-gender-reveal/**",
  "2024/**",
  "baby/**",
  "oliviabday2011/**",
  "passports/**",
  "pt/**",
  "resurrection-challenge/**",
  "sightwords/**",
  "pocketbase/**",
];

export default defineConfig({
  ignorePatterns,
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "import",
    "react",
    "jsx-a11y",
    "node",
    "promise",
  ],
  env: {
    browser: true,
    builtin: true,
  },
  options: {
    typeAware: true,
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
  },
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
    restriction: "off",
    style: "off",
    pedantic: "off",
    nursery: "off",
  },
  rules: {
    "react/react-in-jsx-scope": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/explicit-member-accessibility": "off",
    "typescript/promise-function-async": "off",
    "typescript/no-confusing-void-expression": ["error", { ignoreArrowShorthand: true }],
    "typescript/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "separate-type-imports" },
    ],
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
    "no-await-in-loop": "off",
    "import/no-unassigned-import": "off",
    "import/no-named-as-default-member": "off",
    "import/default": "off",
    "react/no-array-index-key": "off",
    "react/capitalized-calls": "off",
    "react/exhaustive-effect-dependencies": "off",
    "unicorn/prefer-add-event-listener": "off",
    "unicorn/consistent-function-scoping": "off",
    "promise/always-return": "off",
    "promise/no-callback-in-promise": "off",
    "typescript/consistent-return": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "jsx-a11y/prefer-tag-over-role": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "no-console": ["error", { allow: ["error", "warn"] }],
    "no-underscore-dangle": ["error", { allow: ["_id", "_creationTime"] }],
  },
  overrides: [
    {
      files: [
        "scripts/**",
        "vite.config.ts",
        "oxlint.config.ts",
        "oxfmt.config.ts",
        "knip.config.ts",
        "src/passports/**",
        "src/scanify/**",
      ],
      env: {
        node: true,
      },
      rules: {
        "no-console": "off",
      },
    },
  ],
});
