<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/ultrasound-2010-11-02.jpg"><img src="<?php echo $root; ?>assets/images/ultrasound-2010-11-02.jpg" /></a>
<span>Our first ultrasound on November 2nd, 2010.</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/ultrasound-2010-12-28.jpg"><img src="<?php echo $root; ?>assets/images/ultrasound-2010-12-28.jpg" /></a>
<span>Our second ultrasound on December 28th, 2010.</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/ultrasound-1-2011-01-25.jpg"><img src="<?php echo $root; ?>assets/images/ultrasound-1-2011-01-25.jpg" /></a>
<span>3D profile picture from our ultrasound on January 25th, 2011.</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/ultrasound-2-2011-01-25.jpg"><img src="<?php echo $root; ?>assets/images/ultrasound-2-2011-01-25.jpg" /></a>
<span>3D arm and face (partially covered by cord) on January 25th, 2011.</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/comparing-bumps.jpg"><img src="<?php echo $root; ?>assets/images/comparing-bumps.jpg" /></a>
<span>Comparing bumps</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/side-bump-2011-02-13.jpg"><img src="<?php echo $root; ?>assets/images/side-bump-2011-02-13.jpg" /></a>
<span>Olivia's bump on Feb. 13th</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/front-bump-2011-02-13.jpg"><img src="<?php echo $root; ?>assets/images/front-bump-2011-02-13.jpg" /></a>
<span>Olivia's bump on Feb. 13th</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/olivia-mothers-day.jpg"><img src="<?php echo $root; ?>assets/images/olivia-mothers-day.jpg" /></a>
<span>Olivia on Mother's Day at 36 weeks</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/marquette-outfit.jpg"><img src="<?php echo $root; ?>assets/images/marquette-outfit.jpg" /></a>
<span>Baby's first Marquette Outfit</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/mural.jpg"><img src="<?php echo $root; ?>assets/images/mural.jpg" /></a>
<span>Mural in baby's room</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/anniversary-olivia.jpg"><img src="<?php echo $root; ?>assets/images/anniversary-olivia.jpg" /></a>
<span>Olivia on our anniversary, June 2nd.</span>
</div>

<div class="photo small-photo">
<a href="<?php echo $root; ?>assets/images/anniversary-us.jpg"><img src="<?php echo $root; ?>assets/images/anniversary-us.jpg" /></a>
<span>Olivia, Ian, and baby on our anniversary, June 2nd.</span>
</div>

<br class="clear" />